//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiPower.Onlinecol.Standard.Web.SystemManage {
    
    
    public partial class TrainPlanAdd {
        
        /// <summary>
        /// tb_TranPlan 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tb_TranPlan;
        
        /// <summary>
        /// Subject 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx Subject;
        
        /// <summary>
        /// Teacher 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx Teacher;
        
        /// <summary>
        /// ctrArchiveUserList 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlArchiveCheckBoxUserList ctrArchiveUserList;
        
        /// <summary>
        /// PlanDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx PlanDate;
        
        /// <summary>
        /// FinishDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx FinishDate;
        
        /// <summary>
        /// PlanUserName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx PlanUserName;
        
        /// <summary>
        /// btnSave000001 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave000001;
        
        /// <summary>
        /// hid_action 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hid_action;
    }
}
