//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiPower.Onlinecol.Standard.Web.SystemManage {
    
    
    public partial class TrainRecAdd {
        
        /// <summary>
        /// tb_TranRec 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tb_TranRec;
        
        /// <summary>
        /// ddlTrainPlanID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlDropDownTrainPlan ddlTrainPlanID;
        
        /// <summary>
        /// chkArchiveUerList 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlArchiveCheckBoxUserList chkArchiveUerList;
        
        /// <summary>
        /// txtTrainDesc 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx txtTrainDesc;
        
        /// <summary>
        /// txtTrainResult 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlTextBoxEx txtTrainResult;
        
        /// <summary>
        /// btnSave 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        /// <summary>
        /// ctrlBtnBack1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::DigiPower.Onlinecol.Standard.Web.CommonCtrl.ctrlBtnBack ctrlBtnBack1;
    }
}
